covidbooking/covidapp/urls.py
from django.urls import path

from covidapp import views
app_name='covidapp'

urlpatterns = [

path('',views.covidreg,name='covidreg'),
    path('<slug:c_slug>/',views.covidreg,name='places')
    ]

covidbooking/covidbooking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('covidapp.urls')),
    path('credentials/',include('credentials.urls')),
    path('patientdetails/',include('patientdetails.urls')),

    # Login and Logout
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covidbooking/credentials/urls.py
from django.urls import path
from . import views

app_name = "credentials"


urlpatterns = [

    path("register", views.register_request, name="register"),
    path("login",views.login_request,name="login"),
]

covidbooking/patientdetails/urls.py
from django.urls import path
from . import views

app_name = "patientdetails"


urlpatterns = [
    path("detail",views.detail_patient, name="detail_patient"),
    path('success',views.success_page,name="success_page"),
]

covidbooking/covidapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class City(models.Model):
  title = models.CharField(max_length=200)
  url = models.TextField()

  class Meta:
    db_table = 'City'
    ordering = ['title']

  def get_url(self):
    return reverse('covidapp:covidreg', args=[self.City.slug])
  def __str__(self):
    return self.title

covidbooking/credentials/models.py
from django.db import models

# Create your models here.

covidbooking/patientdetails/models.py
# Create your models here.
from django.db import models

# Create your models here.
class PatientsDetails(models.Model):
    name=models.CharField(max_length=250)
    age=models.IntegerField()
    dob=models.DateField()
    address=models.CharField(max_length=250)
    district=models.CharField(max_length=250)
    firstdose=models.BooleanField()
    seconddose=models.BooleanField()

    def __str__(self):
        return  self.name

covidbooking/credentials/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

covidbooking/patientdetails/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms
from.models import PatientsDetails

class PatientForm(forms.ModelForm):
	class Meta:
		model = PatientsDetails
		fields = ['name', 'age','DOB', 'Address','district','Firstdose','SecondDose',]
# Create your forms here.

covidbooking/covidapp/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
# Create your views here.
from .models import City
def covidreg(request,c_slug=None):


    return render(request,"cities.html")

covidbooking/credentials/views.py
from django.shortcuts import  render, redirect
from .forms import NewUserForm


from django.contrib.auth import login, authenticate #add this
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("login")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("login")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="login.html", context={"login_form":form})

covidbooking/patientdetails/views.py
from django.shortcuts import  render, redirect



from django.contrib.auth import login, authenticate #add this
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

from django.shortcuts import  render
def detail_patient(request):
    return render(request,'vaccinationbooking.html')

	# details1 = PatientsDetails.objects.all()
	# # if request.method == 'POST':
	# 	name = request.POST.get('name', '')
	# 	dob = request.POST.get('date', '')
	# 	address=request.POST.get('address','')
	# 	district=request.POST.get('district','')
	# 	Firstdose=request.POST.get('Fisrtdose','')
	# 	Seconddose=request.POST.get('Seconddose','')
    #     patientdetails=Pa

def success_page(request):
    return render(request,'success.html')

covidbooking/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
               <meta name="viewport" content="width=device-width, initial-scale=1 ">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"  >

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

covidbooking/templates/cities.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

Welcome to the covid registration website where you can book vaccination.

{% endblock %}
{% block title %}
 {% if cities %}
      {{cities.name}}
{% endif %}
{% endblock %}
{% block content %}
{% if cities %}

    <div class="row my_row_class">
<a href="{{city.get_url}}"></a>
</div >


<div><a href="{% url 'covidapp:covidreg' %}">Welcome to the vaccination booking site</a>
 </div>
    <div>
</div>




 <br>


{% else %}
<div>
<!--    <img  class="my_image my_image_padding" src="{% static 'img/banners.png' %}" alt="Vaccination Booking Site" height="auto" width="50%" >-->

</div>


{% endif %}
<div>


    </div>
<br>
<br>
<br>
<div>
<div>
<div class="mx_auto">
                  <form class="d-flex" action="{% url 'credentials:login' %}" method="get">

<form class="form-inline my-2 my-lg-0">
    <h3 style="margin-left:350px; margin-bottom:.25;padding-left:100px;"> Book your slot</h3>
     <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
    </form>

                  </form>
</div>
    </div>
<div>
    <div>
        <form class="d-flex" action="{% url 'credentials:register' %}" method="get">

        <form class="form-inline my-2 my-lg-0">
    <h3 style="margin-left:350px; margin-bottom:.25;padding-left:100px;"> New User</h3>
     <button  class="btn btn-outline-success my-2 my-sm-0" type="submit">Register</button>
        </form></form>
    </div></div>



</div>

<br></div>
{% endblock %}

covidbooking/templates/footer.html
<div class="footer fixed-bottom my_footer">
    <p style=" padding-top:20px;
font-size:14px;background-color:#f8f9fa;
height:20px; text-align:center;" >@copyright;CovidRegistrationWebsite.All rights reserved</p>


</div>

covidbooking/templates/header.html
{% load static %}
<header>

    <center>

        <a href="{% url 'covidapp:covidreg' %}" ></a><img src="{% static 'img/banners.png' %}" alt="logoimage" width="200px"height="200px">
    </center>
</header>

covidbooking/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

Welcome to the covid registration website where you can book vaccination.

{% endblock %}
{% block title %}
 {% if cities %}
      {{cities.name}}
{% endif %}
{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<!--Login-->
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
      <a href="{% url 'patientdetails:detail_patient' %}" class="btn btn-success  ">Login</a>

<!--    <button class="btn btn-primary" type="submit">Login</button>-->
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'credentials:register' %}">Create an account</a></p>
</div>

{% endblock %}

covidbooking/templates/navbar.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'covidapp:covidreg' %}"><i class="fas fa-home"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'covidapp:covidreg' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
       <i class="fas fa-city"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kochi">kochi</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvanathapuram">Thiruvananthapuram</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">kollam</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/kasargod">kasargod</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta">Pathanamthitta</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/idukki_district">idukki</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayanad">Wayanad</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad">Palakkad</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">Kannur</a>







      </li>
      <li class="nav-item">
        <a class="nav-link enabled"></a>
      </li>
    </ul>
<!--    <form class="form-inline my-2 my-lg-0">-->
<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
  </div>
</nav>

  </div>

covidbooking/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

Welcome to the covid registration website where you can book vaccination.

{% endblock %}
{% block title %}
 {% if cities %}
      {{cities.name}}
{% endif %}
{% endblock %}
{% block content %}



{% load crispy_forms_tags %}

<!--Register-->






{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'credentials:login' %}">login</a> instead.</p>
</div>

{% endblock %}

covidbooking/templates/success.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

Welcome to the covid registration website where you can book vaccination.

{% endblock %}
{% block title %}
 {% if cities %}
      {{cities.name}}
{% endif %}
{% endblock %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Booking confirmation </title>
</head>
<body style="text-align:center;">
Congratulations Your booking for the vaccination is confirmed.
Thankyou.

</body>
</html>
{% endblock %}

covidbooking/templates/vaccinationbooking.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

Welcome to the covid registration website where you can book vaccination.

{% endblock %}
{% block title %}
 {% if cities %}
      {{cities.name}}
{% endif %}
{% endblock %}
{% block content %}

<!--patient details-->
<div class="container py-5">
	<h1>Details of the patient</h1>
	<form method="POST">
		{% csrf_token %}
		<div class="form-group">
<input type="text" class="form-control" name="patientname" placeholder="Enter your name">

        </div>

		<div class="form-group">
   <input type="number" class="form-control" name="age" placeholder="Enter your age">

</div>
		<div class="form-group">
   <input type="date"  class="form-control" name="DOB" placeholder="Enter Date of birth">

</div>
		<div class="form-group">
   <input type="text" class="form-control" name="Address" placeholder="Enter your address">

</div>
<div class="form-group">
<div class="col-lg-4"><div class="dropdown">


<form action="/action_page.php">
  <label for="cars">Choose a district:</label>
  <select name="cars" id="cars">
         <optgroup label="Kochi">
    <option value="Sunrise Hospital">Sunrise Hospital</option>
    <option value="Kims">Kims</option>
    <option value="Renai medicity">Renai Medicity</option>
    <option value="Aster medicity">Aster medicity</option>
          <option value="Medical college Hospital">Medical College Hospital</option>
             <optgroup label="Kottayam">
                  <option value="Bharath Hospital">Bharath Hospital</option>
          <option value="kottayam malabar hospital">Kottayam malabar hospitall</option>
          <option value="Kottayam medicak college">Kottayam medical college</option>
          <option value="primary health center">Primary health center</option>

              <optgroup label="Pathanamthitta">
                   <option value="District Hospital">district hospital</option>
          <option value="community health center">Community health center</option>
          <option value="General Hospital">General Hospital</option>
          <option value="Sub dist Hospital">Sub dist hospital</option>
                  <optgroup label="Kollam">
                      <option value="thazhava phc">thazhava phc</option>
          <option value="alappad phc">alappad phc</option>
          <option value="k s puram phc">k s puram phc</option>
          <option value="Thodiyoor phc">Thodiyoor phc</option>
                      <optgroup label="Thiruvananthapuram">
                          <option value="azhoor phc">azhoor phc</option>
          <option value="pallikal phc">palikkal phc</option>
          <option value="keshavapuram phc">keshavapuram phc</option>
          <option value="kattakada phc">kattakada phc</option>
                        <optgroup label="Alappuzha">
                            <option value="ambalappuzha">Kozhikode</option>
          <option value="general Hospital">General Hospital</option>
          <option value="medical college">medical college</option>
          <option value="Aryad phc">Aryad phc</option>
                         <optgroup label="Kannur">
                             <option value="pappisseri phc">pappisseri phc</option>
          <option value="w & c hospital">w & c hospital/option>
          <option value="D H kannur">D H kannur</option>
          <option value="Chelora">Chelora phc</option>
                             <optgroup label="Palakkad">
                                 <option value="kuzhalmannam">Kuzhalmannam</option>
          <option value="kavasseri">Kavasseri</option>
          <option value="kannambra">kannambra</option>
          <option value="kuthannur">kuthannur</option>
                                 <optgroup label="Malappuram">
                                     <option value="oorakam">oorakam</option>
          <option value="pallikal">pallikal</option>
          <option value="parappangadi">parappangadi</option>
          <option value="nannambra">nannambra</option>
                                     <optgroup label="Wayanad">
                                         <option value="waniyambara">waniyambara</option>
          <option value="periya">periya</option>
          <option value="panamaram">panamaram</option>
          <option value="vilvattam">vilvattam</option>
                                         <optgroup label="Idukki">
                                             <option value="chithirapuram">chithirapuram</option>
          <option value="rajakkadu">rajakkadu</option>
          <option value="marayur">marayur</option>
          <option value="devikulam">devikulam</option>
                                             <optgroup label="Kasargod">
                                                 <option value="olath">olath</option>
          <option value="konnakadu">Konnakadu</option>
          <option value="madikkai">madikkai</option>
          <option value="kayyur">kayyur</option>
                                                 <optgroup label="Thrissur">
                                                     <option value="kattoor">Kattoor</option>
          <option value="Karalam">Karalam</option>
          <option value="mullasseri">mullasseri</option>
          <option value="valappad">valappad</option>

  </select>
  <br><br>
</form>

</div>



</div>

</div>
        <form action="/action_page.php">
  <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
  <label for="Covishield"> Covishield</label><br>
  <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
  <label for="covaccine"> covaccine</label><br>
  <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat">
  <label for="sputnik"> Sputnik</label><br><br>
            <div class="form-check"></form>
        <div class="form-check">

  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
  <label class="form-check-label" for="flexRadioDefault1">
    First Dose
  </label>
</div>
<div class="form-check">
  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
  <label class="form-check-label" for="flexRadioDefault2">
Second Dose
  </label>
</div>

		<div>


<form class="form-inline my-2 my-lg-0">

    <a href="{% url 'patientdetails:success_page' %}" class="btn btn-success  ">submit details</a>
    </form>

        </div> </form>
</div>




</div>
{% endblock %}